version: '3.8'

services:
    # for development use
    app:
        build: .
        container_name: esteticar-app
 
        volumes:
            - .:/usr/share/app
        ports:
            - 4000:3000
        restart: always
        network_mode: host

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - 6379:6379
        restart: always
        network_mode: host

    redis_insight:
        image: redislabs/redisinsight:latest
        container_name: redis_insight
        restart: always
        ports:
            - 8001:8001
   
    
    # dbeaver:
    #     image: dbeaver/cloudbeaver
    #     container_name: dbeaver
    #     restart: always
    #     ports:
    #         - 80:8090
    #     network_mode: host

    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
            - 8080:8080
        network_mode: host

    postgresql:
        image: postgres
        container_name: postgresql
        ports:
            - 5432:5432
        restart: always
        network_mode: host
        # volumes:
        #     - ./storage/postgresql:var/lib/postgresql/data
        environment:
            - POSTGRES_USER=psqlpass
            - POSTGRES_PASSWORD=psqlpass #pgpass
            # - PGDATA=/var/lib/postgresql/data/pgdata
        # volumes:
        #     - /home/felipe/Documents/esteticar/data:var/lib/postgresql/data
           
           
    # mysql:
    #     image: mysql/mysql-server
    #     container_name: mysql
    #     ports:
    #         - 5432:5432
    #     restart: always
    #     network_mode: host



    
